-- 114 學年度教育部大專校院名錄（廣義校院母表）。
--
-- school_code 是 STA 自有的三位數內碼；000 保留，不使用教育部的學校代碼。
-- 本批次依教育部名錄的校院分類順序重新編號，保留校院類型供後續
-- 招生、論壇與驗證功能篩選。來源：教育部大專校院一覽表（114 學年度）。

ALTER TABLE schools
    ADD COLUMN institution_type VARCHAR(32) NOT NULL DEFAULT 'general_university';

ALTER TABLE schools
    ADD CONSTRAINT schools_institution_type_check CHECK (
        institution_type IN (
            'general_university',
            'technical_institution',
            'junior_college',
            'open_university',
            'religious_research_college'
        )
    );

COMMENT ON COLUMN schools.school_code IS 'STA 自有三位數學校內碼；000 保留為未指定值。';
COMMENT ON COLUMN schools.institution_type IS '教育部廣義大專校院分類。';

INSERT INTO schools (school_code, school_name, institution_type) VALUES
    ('001', '國立政治大學', 'general_university'),
    ('002', '國立清華大學', 'general_university'),
    ('003', '國立臺灣大學', 'general_university'),
    ('004', '國立臺灣師範大學', 'general_university'),
    ('005', '國立成功大學', 'general_university'),
    ('006', '國立中興大學', 'general_university'),
    ('007', '國立陽明交通大學', 'general_university'),
    ('008', '國立中央大學', 'general_university'),
    ('009', '國立中山大學', 'general_university'),
    ('010', '國立臺灣海洋大學', 'general_university'),
    ('011', '國立中正大學', 'general_university'),
    ('012', '國立高雄師範大學', 'general_university'),
    ('013', '國立彰化師範大學', 'general_university'),
    ('014', '國立臺北大學', 'general_university'),
    ('015', '國立嘉義大學', 'general_university'),
    ('016', '國立高雄大學', 'general_university'),
    ('017', '國立東華大學', 'general_university'),
    ('018', '國立暨南國際大學', 'general_university'),
    ('019', '國立臺北藝術大學', 'general_university'),
    ('020', '國立臺灣藝術大學', 'general_university'),
    ('021', '國立臺東大學', 'general_university'),
    ('022', '國立宜蘭大學', 'general_university'),
    ('023', '國立聯合大學', 'general_university'),
    ('024', '國立臺南藝術大學', 'general_university'),
    ('025', '國立臺南大學', 'general_university'),
    ('026', '國立臺北教育大學', 'general_university'),
    ('027', '國立臺中教育大學', 'general_university'),
    ('028', '國立體育大學', 'general_university'),
    ('029', '國立金門大學', 'general_university'),
    ('030', '國立臺灣體育運動大學', 'general_university'),
    ('031', '國立屏東大學', 'general_university'),
    ('032', '臺北市立大學', 'general_university'),
    ('033', '國立臺灣科技大學', 'technical_institution'),
    ('034', '國立雲林科技大學', 'technical_institution'),
    ('035', '國立屏東科技大學', 'technical_institution'),
    ('036', '國立臺北科技大學', 'technical_institution'),
    ('037', '國立虎尾科技大學', 'technical_institution'),
    ('038', '國立澎湖科技大學', 'technical_institution'),
    ('039', '國立勤益科技大學', 'technical_institution'),
    ('040', '國立臺北護理健康大學', 'technical_institution'),
    ('041', '國立高雄餐旅大學', 'technical_institution'),
    ('042', '國立臺中科技大學', 'technical_institution'),
    ('043', '國立臺北商業大學', 'technical_institution'),
    ('044', '國立高雄科技大學', 'technical_institution'),
    ('045', '國立臺灣戲曲學院', 'technical_institution'),
    ('046', '國立臺南護理專科學校', 'junior_college'),
    ('047', '國立臺東專科學校', 'junior_college'),
    ('048', '國立空中大學', 'open_university'),
    ('049', '高雄市立空中大學', 'open_university'),
    ('050', '東海大學', 'general_university'),
    ('051', '輔仁大學', 'general_university'),
    ('052', '東吳大學', 'general_university'),
    ('053', '中原大學', 'general_university'),
    ('054', '淡江大學', 'general_university'),
    ('055', '中國文化大學', 'general_university'),
    ('056', '逢甲大學', 'general_university'),
    ('057', '靜宜大學', 'general_university'),
    ('058', '長庚大學', 'general_university'),
    ('059', '元智大學', 'general_university'),
    ('060', '中華大學', 'general_university'),
    ('061', '大葉大學', 'general_university'),
    ('062', '華梵大學', 'general_university'),
    ('063', '義守大學', 'general_university'),
    ('064', '世新大學', 'general_university'),
    ('065', '銘傳大學', 'general_university'),
    ('066', '實踐大學', 'general_university'),
    ('067', '高雄醫學大學', 'general_university'),
    ('068', '南華大學', 'general_university'),
    ('069', '真理大學', 'general_university'),
    ('070', '大同大學', 'general_university'),
    ('071', '慈濟大學', 'general_university'),
    ('072', '臺北醫學大學', 'general_university'),
    ('073', '中山醫學大學', 'general_university'),
    ('074', '長榮大學', 'general_university'),
    ('075', '中國醫藥大學', 'general_university'),
    ('076', '玄奘大學', 'general_university'),
    ('077', '亞洲大學', 'general_university'),
    ('078', '開南大學', 'general_university'),
    ('079', '佛光大學', 'general_university'),
    ('080', '康寧大學', 'general_university'),
    ('081', '馬偕醫學大學', 'general_university'),
    ('082', '中信金融管理學院', 'general_university'),
    ('083', '法鼓文理學院', 'general_university'),
    ('084', '朝陽科技大學', 'technical_institution'),
    ('085', '南臺科技大學', 'technical_institution'),
    ('086', '崑山科技大學', 'technical_institution'),
    ('087', '嘉南藥理大學', 'technical_institution'),
    ('088', '樹德科技大學', 'technical_institution'),
    ('089', '龍華科技大學', 'technical_institution'),
    ('090', '輔英科技大學', 'technical_institution'),
    ('091', '明新科技大學', 'technical_institution'),
    ('092', '弘光科技大學', 'technical_institution'),
    ('093', '健行科技大學', 'technical_institution'),
    ('094', '正修科技大學', 'technical_institution'),
    ('095', '萬能科技大學', 'technical_institution'),
    ('096', '建國科技大學', 'technical_institution'),
    ('097', '明志科技大學', 'technical_institution'),
    ('098', '台鋼科技大學', 'technical_institution'),
    ('099', '大仁科技大學', 'technical_institution'),
    ('100', '聖約翰科技大學', 'technical_institution'),
    ('101', '嶺東科技大學', 'technical_institution'),
    ('102', '中國科技大學', 'technical_institution'),
    ('103', '中臺科技大學', 'technical_institution'),
    ('104', '台南應用科技大學', 'technical_institution'),
    ('105', '中信科技大學', 'technical_institution'),
    ('106', '元培醫事科技大學', 'technical_institution'),
    ('107', '景文科技大學', 'technical_institution'),
    ('108', '中華醫事科技大學', 'technical_institution'),
    ('109', '東南科技大學', 'technical_institution'),
    ('110', '德明財經科技大學', 'technical_institution'),
    ('111', '南開科技大學', 'technical_institution'),
    ('112', '中華科技大學', 'technical_institution'),
    ('113', '僑光科技大學', 'technical_institution'),
    ('114', '育達科技大學', 'technical_institution'),
    ('115', '美和科技大學', 'technical_institution'),
    ('116', '吳鳳科技大學', 'technical_institution'),
    ('117', '修平科技大學', 'technical_institution'),
    ('118', '長庚科技大學', 'technical_institution'),
    ('119', '臺北城市科技大學', 'technical_institution'),
    ('120', '敏實科技大學', 'technical_institution'),
    ('121', '醒吾科技大學', 'technical_institution'),
    ('122', '文藻外語大學', 'technical_institution'),
    ('123', '華夏科技大學', 'technical_institution'),
    ('124', '致理科技大學', 'technical_institution'),
    ('125', '宏國德霖科技大學', 'technical_institution'),
    ('126', '崇右影藝科技大學', 'technical_institution'),
    ('127', '台北海洋科技大學', 'technical_institution'),
    ('128', '亞東科技大學', 'technical_institution'),
    ('129', '南亞技術學院', 'technical_institution'),
    ('130', '黎明技術學院', 'technical_institution'),
    ('131', '德育護理健康學院', 'technical_institution'),
    ('132', '馬偕醫護管理專科學校', 'junior_college'),
    ('133', '仁德醫護管理專科學校', 'junior_college'),
    ('134', '樹人醫護管理專科學校', 'junior_college'),
    ('135', '慈惠醫護管理專科學校', 'junior_college'),
    ('136', '耕莘健康管理專科學校', 'junior_college'),
    ('137', '敏惠醫護管理專科學校', 'junior_college'),
    ('138', '育英醫護管理專科學校', 'junior_college'),
    ('139', '聖母醫護管理專科學校', 'junior_college'),
    ('140', '新生醫護管理專科學校', 'junior_college'),
    ('141', '崇仁醫護管理專科學校', 'junior_college'),
    ('142', '臺北基督學院', 'religious_research_college'),
    ('143', '中華福音神學研究學院', 'religious_research_college'),
    ('144', '福智佛教學院', 'religious_research_college'),
    ('145', '台灣基督長老教會南神神學院', 'religious_research_college'),
    ('146', '一貫道崇德學院', 'religious_research_college'),
    ('147', '唯心聖教學院', 'religious_research_college'),
    ('148', '台灣神學研究學院', 'religious_research_college'),
    ('149', '基督教台灣浸會神學院', 'religious_research_college')
ON CONFLICT (school_code) DO NOTHING;
