package httpapi

import (
	_ "embed"
	"net/http"
)

// openAPISpec is generated by docs/openapi/generate.py (which writes both
// docs/openapi.json and this copy). Regenerate after changing routes.
//
//go:embed openapi.json
var openAPISpec []byte

// openAPIHandler serves the shallow OpenAPI 3.1 description of /api/v1 so a
// frontend or an API client (Hoppscotch, Insomnia, openapi-generator) can
// scaffold against the real route set.
func openAPIHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "public, max-age=300")
	_, _ = w.Write(openAPISpec)
}
